name: CineScope
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3

  # dependency injection #
    # service locator for DI #
  get_it: ^7.2.0
    # code generator for DI #
  injectable: ^2.1.1

  # handling state management #
  flutter_bloc: ^8.1.2

  # handling navigation #
  go_router: ^6.5.2

  # HTTP client #
  dio: ^5.1.1
    # dio client generator using source_gen
  retrofit: ^4.0.1
    # parse api response
  json_serializable: ^6.3.1

  # local storage #
  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  retrofit_generator: ^6.0.0+1
  injectable_generator: ^2.1.5

  build_runner: ^2.3.3
  hive_generator: ^2.0.0

  # code generation for immutable classes #
  freezed: ^2.3.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
